services:
  swayvnc-chrome:
    build:
      context: .
    container_name: swayvnc-chrome
    environment:
      # replace with GID of the group which owns the /dev/dri/renderD128 device
      - RENDER_GROUP_GID=107
      # optional sway/wayvnc configuration
      - SWAY_RESOLUTION=1920x1080
      - WAYVNC_PORT=5910
      - WAYVNC_ENABLE_AUTH=true
      - WAYVNC_USERNAME=wayvnc
      - WAYVNC_PASSWORD=wayvnc
    volumes:
      - swayvnc-wayvnc-certs:/certs
    privileged: true
    ports:
      - 5910:5910
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    # optional, pass a custom command as an argument to entrypoint.sh to run it under the wayland session
    entrypoint: [
        "/entrypoint.sh",
        # example for running chrome
        "google-chrome-stable",
        "--enable-features=UseOzonePlatform",
        "--ozone-platform=wayland",
        "--disable-dev-shm-usage",
        "--disable-notifications",
        "--disable-popup-blocking",
        "--no-first-run",
        "--disable-fre",
        "--no-default-browser-check",
      ]

volumes:
  swayvnc-wayvnc-certs:
